/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAboutUs {
    }
    interface AppFinanceSite {
    }
    interface AppHome {
    }
    interface AppImprint {
    }
    interface AppPrivacy {
    }
    interface AppRoot {
    }
    interface AppZinsen {
    }
    interface BlogComponent {
        "page"?: string;
    }
    interface BlogList {
    }
    interface CBanner {
        "hidden": boolean;
    }
    interface LatestBlogList {
    }
}
declare global {
    interface HTMLAppAboutUsElement extends Components.AppAboutUs, HTMLStencilElement {
    }
    var HTMLAppAboutUsElement: {
        prototype: HTMLAppAboutUsElement;
        new (): HTMLAppAboutUsElement;
    };
    interface HTMLAppFinanceSiteElement extends Components.AppFinanceSite, HTMLStencilElement {
    }
    var HTMLAppFinanceSiteElement: {
        prototype: HTMLAppFinanceSiteElement;
        new (): HTMLAppFinanceSiteElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppImprintElement extends Components.AppImprint, HTMLStencilElement {
    }
    var HTMLAppImprintElement: {
        prototype: HTMLAppImprintElement;
        new (): HTMLAppImprintElement;
    };
    interface HTMLAppPrivacyElement extends Components.AppPrivacy, HTMLStencilElement {
    }
    var HTMLAppPrivacyElement: {
        prototype: HTMLAppPrivacyElement;
        new (): HTMLAppPrivacyElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppZinsenElement extends Components.AppZinsen, HTMLStencilElement {
    }
    var HTMLAppZinsenElement: {
        prototype: HTMLAppZinsenElement;
        new (): HTMLAppZinsenElement;
    };
    interface HTMLBlogComponentElement extends Components.BlogComponent, HTMLStencilElement {
    }
    var HTMLBlogComponentElement: {
        prototype: HTMLBlogComponentElement;
        new (): HTMLBlogComponentElement;
    };
    interface HTMLBlogListElement extends Components.BlogList, HTMLStencilElement {
    }
    var HTMLBlogListElement: {
        prototype: HTMLBlogListElement;
        new (): HTMLBlogListElement;
    };
    interface HTMLCBannerElement extends Components.CBanner, HTMLStencilElement {
    }
    var HTMLCBannerElement: {
        prototype: HTMLCBannerElement;
        new (): HTMLCBannerElement;
    };
    interface HTMLLatestBlogListElement extends Components.LatestBlogList, HTMLStencilElement {
    }
    var HTMLLatestBlogListElement: {
        prototype: HTMLLatestBlogListElement;
        new (): HTMLLatestBlogListElement;
    };
    interface HTMLElementTagNameMap {
        "app-about-us": HTMLAppAboutUsElement;
        "app-finance-site": HTMLAppFinanceSiteElement;
        "app-home": HTMLAppHomeElement;
        "app-imprint": HTMLAppImprintElement;
        "app-privacy": HTMLAppPrivacyElement;
        "app-root": HTMLAppRootElement;
        "app-zinsen": HTMLAppZinsenElement;
        "blog-component": HTMLBlogComponentElement;
        "blog-list": HTMLBlogListElement;
        "c-banner": HTMLCBannerElement;
        "latest-blog-list": HTMLLatestBlogListElement;
    }
}
declare namespace LocalJSX {
    interface AppAboutUs {
    }
    interface AppFinanceSite {
    }
    interface AppHome {
    }
    interface AppImprint {
    }
    interface AppPrivacy {
    }
    interface AppRoot {
    }
    interface AppZinsen {
    }
    interface BlogComponent {
        "page"?: string;
    }
    interface BlogList {
    }
    interface CBanner {
        "hidden"?: boolean;
    }
    interface LatestBlogList {
    }
    interface IntrinsicElements {
        "app-about-us": AppAboutUs;
        "app-finance-site": AppFinanceSite;
        "app-home": AppHome;
        "app-imprint": AppImprint;
        "app-privacy": AppPrivacy;
        "app-root": AppRoot;
        "app-zinsen": AppZinsen;
        "blog-component": BlogComponent;
        "blog-list": BlogList;
        "c-banner": CBanner;
        "latest-blog-list": LatestBlogList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-about-us": LocalJSX.AppAboutUs & JSXBase.HTMLAttributes<HTMLAppAboutUsElement>;
            "app-finance-site": LocalJSX.AppFinanceSite & JSXBase.HTMLAttributes<HTMLAppFinanceSiteElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-imprint": LocalJSX.AppImprint & JSXBase.HTMLAttributes<HTMLAppImprintElement>;
            "app-privacy": LocalJSX.AppPrivacy & JSXBase.HTMLAttributes<HTMLAppPrivacyElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-zinsen": LocalJSX.AppZinsen & JSXBase.HTMLAttributes<HTMLAppZinsenElement>;
            "blog-component": LocalJSX.BlogComponent & JSXBase.HTMLAttributes<HTMLBlogComponentElement>;
            "blog-list": LocalJSX.BlogList & JSXBase.HTMLAttributes<HTMLBlogListElement>;
            "c-banner": LocalJSX.CBanner & JSXBase.HTMLAttributes<HTMLCBannerElement>;
            "latest-blog-list": LocalJSX.LatestBlogList & JSXBase.HTMLAttributes<HTMLLatestBlogListElement>;
        }
    }
}
