/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAboutUs {
    }
    interface AppFinanceSite {
    }
    interface AppHome {
    }
    interface AppImprint {
    }
    interface AppPrivacy {
    }
    interface AppRoot {
    }
    interface BlogComponent {
        "page"?: string;
    }
    interface BlogList {
    }
    interface CBanner {
        "hidden": boolean;
    }
    interface FooterComp {
    }
    interface HeaderComp {
    }
    interface LatestBlogList {
    }
    interface NavbarComp {
    }
    interface NavbarMenuComp {
        "visible": boolean;
    }
    interface NavbarMenuItemComp {
    }
    interface PageComp {
    }
    interface TextContentComp {
    }
}
declare global {
    interface HTMLAppAboutUsElement extends Components.AppAboutUs, HTMLStencilElement {
    }
    var HTMLAppAboutUsElement: {
        prototype: HTMLAppAboutUsElement;
        new (): HTMLAppAboutUsElement;
    };
    interface HTMLAppFinanceSiteElement extends Components.AppFinanceSite, HTMLStencilElement {
    }
    var HTMLAppFinanceSiteElement: {
        prototype: HTMLAppFinanceSiteElement;
        new (): HTMLAppFinanceSiteElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppImprintElement extends Components.AppImprint, HTMLStencilElement {
    }
    var HTMLAppImprintElement: {
        prototype: HTMLAppImprintElement;
        new (): HTMLAppImprintElement;
    };
    interface HTMLAppPrivacyElement extends Components.AppPrivacy, HTMLStencilElement {
    }
    var HTMLAppPrivacyElement: {
        prototype: HTMLAppPrivacyElement;
        new (): HTMLAppPrivacyElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBlogComponentElement extends Components.BlogComponent, HTMLStencilElement {
    }
    var HTMLBlogComponentElement: {
        prototype: HTMLBlogComponentElement;
        new (): HTMLBlogComponentElement;
    };
    interface HTMLBlogListElement extends Components.BlogList, HTMLStencilElement {
    }
    var HTMLBlogListElement: {
        prototype: HTMLBlogListElement;
        new (): HTMLBlogListElement;
    };
    interface HTMLCBannerElement extends Components.CBanner, HTMLStencilElement {
    }
    var HTMLCBannerElement: {
        prototype: HTMLCBannerElement;
        new (): HTMLCBannerElement;
    };
    interface HTMLFooterCompElement extends Components.FooterComp, HTMLStencilElement {
    }
    var HTMLFooterCompElement: {
        prototype: HTMLFooterCompElement;
        new (): HTMLFooterCompElement;
    };
    interface HTMLHeaderCompElement extends Components.HeaderComp, HTMLStencilElement {
    }
    var HTMLHeaderCompElement: {
        prototype: HTMLHeaderCompElement;
        new (): HTMLHeaderCompElement;
    };
    interface HTMLLatestBlogListElement extends Components.LatestBlogList, HTMLStencilElement {
    }
    var HTMLLatestBlogListElement: {
        prototype: HTMLLatestBlogListElement;
        new (): HTMLLatestBlogListElement;
    };
    interface HTMLNavbarCompElement extends Components.NavbarComp, HTMLStencilElement {
    }
    var HTMLNavbarCompElement: {
        prototype: HTMLNavbarCompElement;
        new (): HTMLNavbarCompElement;
    };
    interface HTMLNavbarMenuCompElement extends Components.NavbarMenuComp, HTMLStencilElement {
    }
    var HTMLNavbarMenuCompElement: {
        prototype: HTMLNavbarMenuCompElement;
        new (): HTMLNavbarMenuCompElement;
    };
    interface HTMLNavbarMenuItemCompElement extends Components.NavbarMenuItemComp, HTMLStencilElement {
    }
    var HTMLNavbarMenuItemCompElement: {
        prototype: HTMLNavbarMenuItemCompElement;
        new (): HTMLNavbarMenuItemCompElement;
    };
    interface HTMLPageCompElement extends Components.PageComp, HTMLStencilElement {
    }
    var HTMLPageCompElement: {
        prototype: HTMLPageCompElement;
        new (): HTMLPageCompElement;
    };
    interface HTMLTextContentCompElement extends Components.TextContentComp, HTMLStencilElement {
    }
    var HTMLTextContentCompElement: {
        prototype: HTMLTextContentCompElement;
        new (): HTMLTextContentCompElement;
    };
    interface HTMLElementTagNameMap {
        "app-about-us": HTMLAppAboutUsElement;
        "app-finance-site": HTMLAppFinanceSiteElement;
        "app-home": HTMLAppHomeElement;
        "app-imprint": HTMLAppImprintElement;
        "app-privacy": HTMLAppPrivacyElement;
        "app-root": HTMLAppRootElement;
        "blog-component": HTMLBlogComponentElement;
        "blog-list": HTMLBlogListElement;
        "c-banner": HTMLCBannerElement;
        "footer-comp": HTMLFooterCompElement;
        "header-comp": HTMLHeaderCompElement;
        "latest-blog-list": HTMLLatestBlogListElement;
        "navbar-comp": HTMLNavbarCompElement;
        "navbar-menu-comp": HTMLNavbarMenuCompElement;
        "navbar-menu-item-comp": HTMLNavbarMenuItemCompElement;
        "page-comp": HTMLPageCompElement;
        "text-content-comp": HTMLTextContentCompElement;
    }
}
declare namespace LocalJSX {
    interface AppAboutUs {
    }
    interface AppFinanceSite {
    }
    interface AppHome {
    }
    interface AppImprint {
    }
    interface AppPrivacy {
    }
    interface AppRoot {
    }
    interface BlogComponent {
        "page"?: string;
    }
    interface BlogList {
    }
    interface CBanner {
        "hidden"?: boolean;
    }
    interface FooterComp {
    }
    interface HeaderComp {
    }
    interface LatestBlogList {
    }
    interface NavbarComp {
    }
    interface NavbarMenuComp {
        "visible"?: boolean;
    }
    interface NavbarMenuItemComp {
    }
    interface PageComp {
    }
    interface TextContentComp {
    }
    interface IntrinsicElements {
        "app-about-us": AppAboutUs;
        "app-finance-site": AppFinanceSite;
        "app-home": AppHome;
        "app-imprint": AppImprint;
        "app-privacy": AppPrivacy;
        "app-root": AppRoot;
        "blog-component": BlogComponent;
        "blog-list": BlogList;
        "c-banner": CBanner;
        "footer-comp": FooterComp;
        "header-comp": HeaderComp;
        "latest-blog-list": LatestBlogList;
        "navbar-comp": NavbarComp;
        "navbar-menu-comp": NavbarMenuComp;
        "navbar-menu-item-comp": NavbarMenuItemComp;
        "page-comp": PageComp;
        "text-content-comp": TextContentComp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-about-us": LocalJSX.AppAboutUs & JSXBase.HTMLAttributes<HTMLAppAboutUsElement>;
            "app-finance-site": LocalJSX.AppFinanceSite & JSXBase.HTMLAttributes<HTMLAppFinanceSiteElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-imprint": LocalJSX.AppImprint & JSXBase.HTMLAttributes<HTMLAppImprintElement>;
            "app-privacy": LocalJSX.AppPrivacy & JSXBase.HTMLAttributes<HTMLAppPrivacyElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "blog-component": LocalJSX.BlogComponent & JSXBase.HTMLAttributes<HTMLBlogComponentElement>;
            "blog-list": LocalJSX.BlogList & JSXBase.HTMLAttributes<HTMLBlogListElement>;
            "c-banner": LocalJSX.CBanner & JSXBase.HTMLAttributes<HTMLCBannerElement>;
            "footer-comp": LocalJSX.FooterComp & JSXBase.HTMLAttributes<HTMLFooterCompElement>;
            "header-comp": LocalJSX.HeaderComp & JSXBase.HTMLAttributes<HTMLHeaderCompElement>;
            "latest-blog-list": LocalJSX.LatestBlogList & JSXBase.HTMLAttributes<HTMLLatestBlogListElement>;
            "navbar-comp": LocalJSX.NavbarComp & JSXBase.HTMLAttributes<HTMLNavbarCompElement>;
            "navbar-menu-comp": LocalJSX.NavbarMenuComp & JSXBase.HTMLAttributes<HTMLNavbarMenuCompElement>;
            "navbar-menu-item-comp": LocalJSX.NavbarMenuItemComp & JSXBase.HTMLAttributes<HTMLNavbarMenuItemCompElement>;
            "page-comp": LocalJSX.PageComp & JSXBase.HTMLAttributes<HTMLPageCompElement>;
            "text-content-comp": LocalJSX.TextContentComp & JSXBase.HTMLAttributes<HTMLTextContentCompElement>;
        }
    }
}
